#!/usr/bin/env python3
"""Convert a metric height-map NPZ into directional and total terrain cost maps.

The input is the NPZ generated by ``heightmap_generator.py``. Costs are based on
terrain gradient (slope) and local curvature / roughness (Laplacian). Unknown
height-map cells remain unknown and are stored as ``-1`` in the cost grids.
"""

from __future__ import annotations

import argparse
import csv
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Sequence

import numpy as np

try:
    from PIL import Image
except ImportError:  # pragma: no cover
    Image = None


@dataclass(frozen=True)
class GradientData:
    x: np.ndarray
    y: np.ndarray
    magnitude: np.ndarray
    laplacian: np.ndarray


@dataclass(frozen=True)
class CostData:
    total: np.ndarray
    x: np.ndarray
    y: np.ndarray


def _fill_unknown_nearest(grid: np.ndarray) -> np.ndarray:
    """Fill NaNs for derivative calculation while preserving the original mask.

    This dependency-free nearest-neighbour propagation is intentionally simple
    because the Mars Yard grids are small. Unknown cells are restored to -1 in
    the final cost map, so filled values are only used to avoid NaN gradients at
    valid-cell borders.
    """
    filled = np.asarray(grid, dtype=np.float64).copy()
    missing = np.isnan(filled)
    if not np.any(missing):
        return filled
    if np.all(missing):
        raise ValueError("height map contains no valid cells")

    # Repeatedly copy the mean of valid 8-neighbours into currently unknown cells.
    # The loop converges quickly for the map dimensions used by this package.
    while np.any(np.isnan(filled)):
        valid = ~np.isnan(filled)
        sums = np.zeros_like(filled)
        counts = np.zeros_like(filled, dtype=np.int16)
        for dy in (-1, 0, 1):
            for dx in (-1, 0, 1):
                if dx == 0 and dy == 0:
                    continue
                shifted = np.roll(np.roll(filled, dy, axis=0), dx, axis=1)
                shifted_valid = np.roll(np.roll(valid, dy, axis=0), dx, axis=1)
                # Remove wrap-around neighbours introduced by np.roll.
                if dy > 0:
                    shifted_valid[:dy, :] = False
                elif dy < 0:
                    shifted_valid[dy:, :] = False
                if dx > 0:
                    shifted_valid[:, :dx] = False
                elif dx < 0:
                    shifted_valid[:, dx:] = False
                sums[shifted_valid] += shifted[shifted_valid]
                counts[shifted_valid] += 1
        update = np.isnan(filled) & (counts > 0)
        if not np.any(update):
            break
        filled[update] = sums[update] / counts[update]
    return filled


def calculate_gradients(height_grid: np.ndarray, resolution: float) -> GradientData:
    if resolution <= 0:
        raise ValueError("resolution must be positive")
    filled = _fill_unknown_nearest(height_grid)
    grad_y, grad_x = np.gradient(filled, resolution, resolution)
    magnitude = np.hypot(grad_x, grad_y)
    d2x = np.gradient(grad_x, resolution, axis=1)
    d2y = np.gradient(grad_y, resolution, axis=0)
    laplacian = d2x + d2y
    return GradientData(grad_x, grad_y, magnitude, laplacian)


def calculate_costs(
    gradients: GradientData,
    valid_mask: np.ndarray,
    *,
    gradient_scale: float = 150.0,
    stability_scale: float = 90.0,
    gradient_reference: float = 1.0,
    stability_reference: float = 1.0,
) -> CostData:
    if gradient_reference <= 0 or stability_reference <= 0:
        raise ValueError("gradient and stability reference values must be positive")

    stability = np.abs(gradients.laplacian)
    gradient_cost = (gradients.magnitude / gradient_reference) * gradient_scale
    stability_cost = (stability / stability_reference) * stability_scale

    total = np.clip(gradient_cost + stability_cost, 0.0, 100.0)
    cost_x = np.clip(
        (np.abs(gradients.x) / gradient_reference) * gradient_scale + stability_cost,
        0.0,
        100.0,
    )
    cost_y = np.clip(
        (np.abs(gradients.y) / gradient_reference) * gradient_scale + stability_cost,
        0.0,
        100.0,
    )

    for grid in (total, cost_x, cost_y):
        grid[~valid_mask] = -1.0

    return CostData(
        np.rint(total).astype(np.int16),
        np.rint(cost_x).astype(np.int16),
        np.rint(cost_y).astype(np.int16),
    )


def _write_csv(path: str, grid: np.ndarray) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow([""] + [str(index) for index in range(grid.shape[1])])
        for row_index, row in enumerate(grid):
            writer.writerow([str(row_index)] + [str(int(value)) for value in row])


def _write_preview(path: str, costs: CostData) -> None:
    if Image is None:
        return
    panels = []
    for grid in (costs.total, costs.x, costs.y):
        image = np.full(grid.shape, 128, dtype=np.uint8)  # unknown = grey
        valid = grid >= 0
        image[valid] = np.clip(np.rint(grid[valid] * 2.55), 0, 255).astype(np.uint8)
        panels.append(np.flipud(image))
    combined = np.concatenate(panels, axis=1)
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    Image.fromarray(combined, mode="L").save(path)


def generate_costmap_from_heightmap(
    heightmap_path: str,
    output_path: str,
    *,
    preview_path: Optional[str] = None,
    csv_directory: Optional[str] = None,
    gradient_scale: float = 150.0,
    stability_scale: float = 90.0,
    gradient_reference: float = 1.0,
    stability_reference: float = 1.0,
) -> str:
    heightmap_path = os.path.abspath(os.path.expanduser(heightmap_path))
    output_path = os.path.abspath(os.path.expanduser(output_path))
    if not os.path.isfile(heightmap_path):
        raise FileNotFoundError(f"Height map not found: {heightmap_path}")

    source = np.load(heightmap_path, allow_pickle=False)
    required = {"grid", "resolution", "origin_x", "origin_y"}
    missing = required.difference(source.files)
    if missing:
        raise ValueError(f"Height map is missing required arrays: {sorted(missing)}")

    height_grid = np.asarray(source["grid"], dtype=np.float64)
    resolution = float(np.asarray(source["resolution"]).item())
    valid_mask = ~np.isnan(height_grid)
    gradients = calculate_gradients(height_grid, resolution)
    costs = calculate_costs(
        gradients,
        valid_mask,
        gradient_scale=gradient_scale,
        stability_scale=stability_scale,
        gradient_reference=gradient_reference,
        stability_reference=stability_reference,
    )

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    np.savez_compressed(
        output_path,
        total=costs.total,
        cost_x=costs.x,
        cost_y=costs.y,
        gradient_x=gradients.x.astype(np.float32),
        gradient_y=gradients.y.astype(np.float32),
        gradient_magnitude=gradients.magnitude.astype(np.float32),
        laplacian=gradients.laplacian.astype(np.float32),
        resolution=np.float64(resolution),
        origin_x=np.float64(np.asarray(source["origin_x"]).item()),
        origin_y=np.float64(np.asarray(source["origin_y"]).item()),
        heightmap_path=np.asarray(heightmap_path),
        gradient_scale=np.float64(gradient_scale),
        stability_scale=np.float64(stability_scale),
        gradient_reference=np.float64(gradient_reference),
        stability_reference=np.float64(stability_reference),
    )

    if csv_directory:
        csv_directory = os.path.abspath(os.path.expanduser(csv_directory))
        _write_csv(os.path.join(csv_directory, "cost_x.csv"), costs.x)
        _write_csv(os.path.join(csv_directory, "cost_y.csv"), costs.y)
        _write_csv(os.path.join(csv_directory, "total_cost.csv"), costs.total)
    if preview_path:
        preview_path = os.path.abspath(os.path.expanduser(preview_path))
        _write_preview(preview_path, costs)

    valid_costs = costs.total[costs.total >= 0]
    print("=" * 60)
    print("Generated terrain cost map from height map")
    print(f"Heightmap:   {heightmap_path}")
    print(f"Output:      {output_path}")
    if preview_path:
        print(f"Preview:     {preview_path}")
    if csv_directory:
        print(f"CSV folder:  {csv_directory}")
    print(f"Resolution:  {resolution:.3f} m/cell")
    print(f"Grid:        {height_grid.shape[1]} x {height_grid.shape[0]}")
    if valid_costs.size:
        print(f"Cost range:  {int(valid_costs.min())} .. {int(valid_costs.max())}")
    print(f"Unknown:     {int((costs.total < 0).sum())}")
    print("=" * 60)
    return output_path


def build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Convert a metric height-map NPZ into terrain cost maps."
    )
    parser.add_argument("heightmap", help="input height-map .npz")
    parser.add_argument("-o", "--output", required=True, help="output cost-map .npz")
    parser.add_argument("--preview", help="optional preview PNG (total, X, Y panels)")
    parser.add_argument("--csv-dir", help="optional folder for cost_x.csv, cost_y.csv and total_cost.csv")
    parser.add_argument("--gradient-scale", type=float, default=150.0)
    parser.add_argument("--stability-scale", type=float, default=90.0)
    parser.add_argument(
        "--gradient-reference",
        type=float,
        default=1.0,
        help="gradient magnitude that receives gradient_scale cost (default: 1.0 m/m)",
    )
    parser.add_argument(
        "--stability-reference",
        type=float,
        default=1.0,
        help="absolute Laplacian that receives stability_scale cost (default: 1.0 m/m²)",
    )
    return parser


def main(argv: Optional[Sequence[str]] = None) -> None:
    parser = build_argument_parser()
    args = parser.parse_args(argv)
    if not args.output.lower().endswith(".npz"):
        parser.error("the output file must use the .npz extension")
    generate_costmap_from_heightmap(
        args.heightmap,
        args.output,
        preview_path=args.preview,
        csv_directory=args.csv_dir,
        gradient_scale=args.gradient_scale,
        stability_scale=args.stability_scale,
        gradient_reference=args.gradient_reference,
        stability_reference=args.stability_reference,
    )


if __name__ == "__main__":
    main()
